'use strict';
const COLORS = Object.freeze({
  'mocap-left': '#42deef', 'mocap-right': '#f06be6',
  'imu-left': '#67efa5', 'imu-right': '#ffc15a',
  outline: 'rgba(2,7,13,.88)', grid: 'rgba(118,165,198,.11)', gridStrong: 'rgba(118,185,215,.22)'
});
const DEFAULT_VIEW = Object.freeze({yaw:-0.48,pitch:-0.56,zoom:1,panX:0,panY:0});
const MOTION_LAYERS = Object.freeze([{"id":"mocap-left","kind":"mocap","side":"left","joint_offset":0,"joint_count":11,"chains":[[0,2,1],[0,4,3],[0,6,5],[0,8,7],[0,10,9]]},{"id":"mocap-right","kind":"mocap","side":"right","joint_offset":11,"joint_count":11,"chains":[[0,2,1],[0,4,3],[0,6,5],[0,8,7],[0,10,9]]},{"id":"imu-left","kind":"result","side":"left","joint_offset":22,"joint_count":20,"chains":[[0,1,2,3],[0,4,5,6,7],[0,8,9,10,11],[0,12,13,14,15],[0,16,17,18,19]]},{"id":"imu-right","kind":"result","side":"right","joint_offset":42,"joint_count":20,"chains":[[0,1,2,3],[0,4,5,6,7],[0,8,9,10,11],[0,12,13,14,15],[0,16,17,18,19]]}]);
const state = {rows:[],row:null,motion:null,generation:0,frame:0,buffer:null,view:{...DEFAULT_VIEW},tool:'orbit',drag:null,abort:null};
const dom = {take:document.querySelector('#take'),method:document.querySelector('#method'),player:document.querySelector('#player'),canvas:document.querySelector('#motion-canvas'),timeline:document.querySelector('#timeline'),orbit:document.querySelector('#orbit-mode'),pan:document.querySelector('#pan-mode'),reset:document.querySelector('#reset-view'),load:document.querySelector('#load-state'),frame:document.querySelector('#frame-readout'),view:document.querySelector('#view-readout'),time:document.querySelector('#time-readout')};
const ctx = dom.canvas.getContext('2d',{alpha:false});
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
function hex(buffer){return Array.from(new Uint8Array(buffer),b=>b.toString(16).padStart(2,'0')).join('');}
async function fetchJson(url,sha,signal){const response=await fetch(url,{cache:'no-store',signal});if(!response.ok)throw new Error(`${url} HTTP ${response.status}`);const bytes=await response.arrayBuffer();if(sha&&globalThis.crypto?.subtle){const digest=await crypto.subtle.digest('SHA-256',bytes);if(hex(digest)!==sha)throw new Error(`${url} SHA mismatch`);}return JSON.parse(new TextDecoder().decode(bytes));}
function validateMotion(m,row){if(m?.schema!=='gt_calib.imu_mocap_visualization_motion.v1'||m.take_id!==row.take_id||m.method_id!==row.method_id||m.frame_count!==row.frame_count||m.fps!==30||m.units!=='mm'||!Array.isArray(m.layers)||JSON.stringify(m.layers)!==JSON.stringify(MOTION_LAYERS)||!Array.isArray(m.frames)||m.frames.length!==row.frame_count)throw new Error('3D motion contract mismatch');const e=m.encoding;if(e?.kind!=='frame-major-flat-int32-json'||e.components!=='XYZ'||!Number.isFinite(e.quantum_mm)||e.quantum_mm<=0||!Array.isArray(e.origin_mm)||e.origin_mm.length!==3||e.joint_count!==62||e.values_per_frame!==186||!m.frames.every(frame=>Array.isArray(frame)&&frame.length===186&&frame.every(Number.isInteger)))throw new Error('3D encoding mismatch');}
function selectedRow(){return state.rows.find(r=>r.take_id===dom.take.value&&r.method_id===dom.method.value);}
async function update(){const row=selectedRow();if(!row)return;const previous=state.row,desiredFrame=previous?.take_id===row.take_id?state.frame:0,resume=previous!==null&&!dom.player.paused&&!dom.player.ended,generation=++state.generation;if(state.abort)state.abort.abort();state.abort=new AbortController();state.row=row;state.motion=null;state.buffer=null;dom.load.textContent='正在校验 3D motion…';dom.timeline.disabled=true;dom.player.pause();clearCanvas();dom.player.poster=row.poster;dom.player.src=`videos/${row.filename}`;document.querySelector('#kind').textContent=row.supervision==='imu_only'?'IMU articulation · MOCAP-calibrated':row.supervision;document.querySelector('#title').textContent=`${row.take_label} · ${row.method_label}`;document.querySelector('#median').textContent=`${row.summary.reference_median_mm.toFixed(3)} mm`;document.querySelector('#p95').textContent=`${row.summary.reference_p95_mm.toFixed(3)} mm`;document.querySelector('#jitter').textContent=`${row.summary.jitter_p95_mm.toFixed(3)} mm`;document.querySelector('#download').href=`videos/${row.filename}`;document.querySelector('#motion-download').href=row.motion;document.querySelector('#metrics').href=row.metrics;try{const motion=await fetchJson(row.motion,row.motion_sha256,state.abort.signal);if(generation!==state.generation)return;validateMotion(motion,row);state.motion=motion;state.buffer=new Float32Array(motion.encoding.joint_count*3);state.frame=clamp(desiredFrame,0,row.frame_count-1);dom.timeline.max=String(row.frame_count-1);dom.timeline.value=String(state.frame);dom.timeline.disabled=false;if(!previous||previous.take_id!==row.take_id)state.view={...DEFAULT_VIEW};drawFrame(state.frame);const seek=()=>{if(generation!==state.generation)return;dom.player.currentTime=state.frame/state.motion.fps;if(resume)dom.player.play().catch(()=>{});};if(dom.player.readyState>=1)seek();else dom.player.addEventListener('loadedmetadata',seek,{once:true});dom.load.textContent=`3D ready · ${motion.encoding.joint_count} joints · ${row.frame_count} frames`;armVideoClock(generation);}catch(error){if(generation!==state.generation)return;console.error(error);clearCanvas();dom.load.textContent=`3D 加载失败：${error.message}`;}}
function decodeFrame(index){const m=state.motion;const frame=m.frames[index];const q=m.encoding.quantum_mm,o=m.encoding.origin_mm,b=state.buffer;for(let i=0;i<b.length;i++)b[i]=o[i%3]+frame[i]*q;return b;}
function ensureResolution(){const rect=dom.canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1),w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(dom.canvas.width!==w||dom.canvas.height!==h){dom.canvas.width=w;dom.canvas.height=h;}return {w,h,dpr};}
function clearCanvas(){const {w,h}=ensureResolution();ctx.fillStyle='#050c14';ctx.fillRect(0,0,w,h);dom.frame.textContent='FRAME —';dom.view.textContent='3D —';}
function layerById(id){return state.motion.layers.find(layer=>layer.id===id);}
function joint(buffer,index){const i=index*3;return [buffer[i],buffer[i+1],buffer[i+2]];}
function drawFrame(requested){if(!state.motion)return;state.frame=clamp(Math.round(requested),0,state.motion.frame_count-1);decodeFrame(state.frame);dom.timeline.value=String(state.frame);dom.frame.textContent=`FRAME ${state.frame} / ${state.motion.frame_count-1}`;dom.time.textContent=formatTime(state.frame/state.motion.fps);drawScene();}
function formatTime(value){const minutes=Math.floor(value/60),seconds=value-minutes*60;return `${String(minutes).padStart(2,'0')}:${seconds.toFixed(3).padStart(6,'0')}`;}
function drawScene(){if(!state.motion)return;const {w,h}=ensureResolution(),b=state.buffer,left=layerById('mocap-left'),right=layerById('mocap-right'),a=joint(b,left.joint_offset),c=joint(b,right.joint_offset),center=[(a[0]+c[0])/2,(a[1]+c[1])/2,(a[2]+c[2])/2],extent=state.motion.view.reference_extent_mm,scale=Math.min(w,h)/(2*extent)*state.view.zoom;ctx.fillStyle='#050c14';ctx.fillRect(0,0,w,h);drawGrid(w,h);const cy=Math.cos(state.view.yaw),sy=Math.sin(state.view.yaw),cp=Math.cos(state.view.pitch),sp=Math.sin(state.view.pitch),projected=[];for(let i=0;i<b.length;i+=3){const x=b[i]-center[0],y=b[i+1]-center[1],z=b[i+2]-center[2],yx=cy*x+sy*z,yz=-sy*x+cy*z,py=cp*y-sp*yz,pz=sp*y+cp*yz;projected.push({x:w/2+yx*scale+state.view.panX,y:h/2-py*scale+state.view.panY,z:pz});}const bones=[];for(const layer of state.motion.layers){for(const chain of layer.chains){for(let i=0;i<chain.length-1;i++){const u=layer.joint_offset+chain[i],v=layer.joint_offset+chain[i+1];bones.push({u,v,id:layer.id,kind:layer.kind,depth:(projected[u].z+projected[v].z)/2});}}}bones.sort((x,y)=>x.depth-y.depth);ctx.lineCap='round';ctx.lineJoin='round';for(const bone of bones){const u=projected[bone.u],v=projected[bone.v];ctx.beginPath();ctx.moveTo(u.x,u.y);ctx.lineTo(v.x,v.y);ctx.lineWidth=bone.kind==='mocap'?7:6;ctx.strokeStyle=COLORS.outline;ctx.stroke();ctx.beginPath();ctx.moveTo(u.x,u.y);ctx.lineTo(v.x,v.y);ctx.lineWidth=bone.kind==='mocap'?2.2:3.2;ctx.strokeStyle=COLORS[bone.id];ctx.setLineDash(bone.kind==='mocap'?[6,3]:[]);ctx.stroke();ctx.setLineDash([]);}const nodes=[];for(const layer of state.motion.layers){for(let i=0;i<layer.joint_count;i++){const index=layer.joint_offset+i;nodes.push({index,id:layer.id,kind:layer.kind,depth:projected[index].z});}}nodes.sort((x,y)=>x.depth-y.depth);for(const node of nodes){const p=projected[node.index];ctx.beginPath();ctx.arc(p.x,p.y,node.kind==='mocap'?4:3.2,0,Math.PI*2);ctx.lineWidth=2;ctx.strokeStyle=COLORS[node.id];if(node.kind==='mocap'){ctx.fillStyle='#07111b';ctx.fill();ctx.stroke();}else{ctx.fillStyle=COLORS[node.id];ctx.fill();}}drawAxes(w,h,cy,sy,cp,sp);dom.view.textContent=`yaw ${(state.view.yaw*180/Math.PI).toFixed(0)}° · pitch ${(state.view.pitch*180/Math.PI).toFixed(0)}° · ${state.view.zoom.toFixed(2)}×`;}
function drawGrid(w,h){ctx.strokeStyle=COLORS.grid;ctx.lineWidth=1;const step=Math.max(28,Math.round(Math.min(w,h)/12));for(let x=w/2%step;x<w;x+=step){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=h/2%step;y<h;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.strokeStyle=COLORS.gridStrong;ctx.beginPath();ctx.moveTo(w/2,0);ctx.lineTo(w/2,h);ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke();}
function drawAxes(w,h,cy,sy,cp,sp){const ox=w-42,oy=h-39,len=22,axes=[['X',[1,0,0],'#ff7e89'],['Y',[0,1,0],'#7de7ad'],['Z',[0,0,1],'#79a9ff']];ctx.font='700 9px ui-monospace,monospace';for(const [label,[x,y,z],color] of axes){const yx=cy*x+sy*z,yz=-sy*x+cy*z,py=cp*y-sp*yz;ctx.beginPath();ctx.moveTo(ox,oy);ctx.lineTo(ox+yx*len,oy-py*len);ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle=color;ctx.fillText(label,ox+yx*len+3,oy-py*len+3);}}
function resetView(){state.view={...DEFAULT_VIEW};drawScene();}
function setTool(tool){state.tool=tool;dom.orbit.classList.toggle('active',tool==='orbit');dom.pan.classList.toggle('active',tool==='pan');dom.orbit.setAttribute('aria-pressed',String(tool==='orbit'));dom.pan.setAttribute('aria-pressed',String(tool==='pan'));}
function syncVideo(){if(!state.motion||!Number.isFinite(dom.player.currentTime))return;drawFrame(Math.round(dom.player.currentTime*state.motion.fps));}
function armVideoClock(generation){if(!('requestVideoFrameCallback' in dom.player))return;dom.player.requestVideoFrameCallback((_now,metadata)=>{if(generation!==state.generation)return;drawFrame(Math.round(metadata.mediaTime*state.motion.fps));armVideoClock(generation);});}
dom.take.addEventListener('change',update);dom.method.addEventListener('change',update);dom.timeline.addEventListener('input',()=>{if(!state.motion)return;drawFrame(Number(dom.timeline.value));dom.player.currentTime=state.frame/state.motion.fps;});for(const event of ['loadeddata','seeked','timeupdate'])dom.player.addEventListener(event,syncVideo);dom.orbit.addEventListener('click',()=>setTool('orbit'));dom.pan.addEventListener('click',()=>setTool('pan'));dom.reset.addEventListener('click',resetView);dom.canvas.addEventListener('pointerdown',event=>{if(!state.motion)return;event.preventDefault();dom.canvas.setPointerCapture(event.pointerId);dom.canvas.dataset.dragging='true';state.drag={id:event.pointerId,x:event.clientX,y:event.clientY,mode:event.shiftKey||event.button!==0?'pan':state.tool};});dom.canvas.addEventListener('pointermove',event=>{if(!state.drag||state.drag.id!==event.pointerId)return;const dx=event.clientX-state.drag.x,dy=event.clientY-state.drag.y;state.drag.x=event.clientX;state.drag.y=event.clientY;if(state.drag.mode==='pan'){state.view.panX+=dx*(devicePixelRatio||1);state.view.panY+=dy*(devicePixelRatio||1);}else{state.view.yaw+=dx*.008;state.view.pitch=clamp(state.view.pitch+dy*.008,-1.48,1.48);}drawScene();});function endDrag(event){if(state.drag?.id===event.pointerId){state.drag=null;delete dom.canvas.dataset.dragging;}}dom.canvas.addEventListener('pointerup',endDrag);dom.canvas.addEventListener('pointercancel',endDrag);dom.canvas.addEventListener('contextmenu',event=>event.preventDefault());dom.canvas.addEventListener('wheel',event=>{event.preventDefault();state.view.zoom=clamp(state.view.zoom*Math.exp(-event.deltaY*.001),.25,6);drawScene();},{passive:false});dom.canvas.addEventListener('dblclick',resetView);new ResizeObserver(()=>{if(state.motion)drawScene();else clearCanvas();}).observe(dom.canvas);setTool('orbit');clearCanvas();fetch('manifest.json').then(response=>{if(!response.ok)throw new Error(`manifest HTTP ${response.status}`);return response.json();}).then(manifest=>{state.rows=manifest.videos;update();}).catch(error=>{console.error(error);dom.load.textContent=`加载失败：${error.message}`;});
